package projetoprog;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kesley
 */
public class GUI extends javax.swing.JFrame {
    String passwd;
    String[] VetorVacinas = new String[30];
    /**
     * Creates new form GUI
     */
    public GUI() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogoErroLogin = new javax.swing.JDialog();
        ErroDialogo = new javax.swing.JLabel();
        BotaoOkDialogoErro = new javax.swing.JButton();
        BemVindoDialogo = new javax.swing.JDialog();
        BotaoOkDialogoSucesso = new javax.swing.JButton();
        TextoSucessoDialogo = new javax.swing.JLabel();
        DialogoErroAplic = new javax.swing.JDialog();
        ErroDialogo1 = new javax.swing.JLabel();
        BotaoOkErroAplic = new javax.swing.JButton();
        GrupoSexo = new javax.swing.ButtonGroup();
        FrameLogin = new javax.swing.JPanel();
        CampoUsuario = new javax.swing.JTextField();
        CampoSenha = new javax.swing.JPasswordField();
        botaologin = new javax.swing.JLabel();
        LogoSoftware = new javax.swing.JLabel();
        IconUser = new javax.swing.JLabel();
        IconPass = new javax.swing.JLabel();
        FrameMenuPrincipal = new javax.swing.JPanel();
        MenuTabs = new javax.swing.JTabbedPane();
        PainelCadastrarPaciente = new javax.swing.JPanel();
        TextoNome = new javax.swing.JLabel();
        TextoDataNascimento = new javax.swing.JLabel();
        TextoSexo = new javax.swing.JLabel();
        CampoNome = new javax.swing.JTextField();
        CampoDataDeNascimento = new javax.swing.JFormattedTextField();
        BotaoSalvarCadastro = new javax.swing.JButton();
        BotaoLimparCadastro = new javax.swing.JButton();
        BotaoMasculino = new javax.swing.JRadioButton();
        BotaoFeminino = new javax.swing.JRadioButton();
        PainelAplicarVacinas = new javax.swing.JPanel();
        TextoNomeAplic = new javax.swing.JLabel();
        CampoNomeAplic = new javax.swing.JTextField();
        TextoVacina = new javax.swing.JLabel();
        DataAplic = new javax.swing.JLabel();
        CaixaFebreAmarela = new javax.swing.JCheckBox();
        CaixaHPV = new javax.swing.JCheckBox();
        CaixaTripliceViral = new javax.swing.JCheckBox();
        CaixaAntiTetanica = new javax.swing.JCheckBox();
        CaixaHepatiteB = new javax.swing.JCheckBox();
        CaixaTetraViral = new javax.swing.JCheckBox();
        CaixaPentavalente = new javax.swing.JCheckBox();
        CaixaBCG = new javax.swing.JCheckBox();
        CaixadTpa = new javax.swing.JCheckBox();
        CaixaGripe = new javax.swing.JCheckBox();
        CampoDataAplic = new javax.swing.JTextField();
        BotaoSalvarAplic = new javax.swing.JButton();
        BotaoLimparAplic = new javax.swing.JButton();
        PainelVisualizarCarteira = new javax.swing.JPanel();
        LabelNomeBuscarCarteira = new javax.swing.JLabel();
        CampoNomeBuscarCarteira = new javax.swing.JTextField();
        BotaoBuscarCarteira = new javax.swing.JButton();
        TextoVacinas = new javax.swing.JTextArea();
        TextoData = new javax.swing.JTextArea();
        TextoColunaVacina = new javax.swing.JTextField();
        TextoColunaDataDeVacinacao = new javax.swing.JTextField();

        DialogoErroLogin.setAlwaysOnTop(false);

        ErroDialogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ErroDialogo.setText("Usuário/Senha Incorreto(s)!");

        BotaoOkDialogoErro.setText("OK");
        BotaoOkDialogoErro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoOkDialogoErroMouseClicked(evt);
            }
        });
        BotaoOkDialogoErro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoOkDialogoErroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogoErroLoginLayout = new javax.swing.GroupLayout(DialogoErroLogin.getContentPane());
        DialogoErroLogin.getContentPane().setLayout(DialogoErroLoginLayout);
        DialogoErroLoginLayout.setHorizontalGroup(
            DialogoErroLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoErroLoginLayout.createSequentialGroup()
                .addGroup(DialogoErroLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogoErroLoginLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(BotaoOkDialogoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DialogoErroLoginLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(ErroDialogo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(123, 123, 123))
        );
        DialogoErroLoginLayout.setVerticalGroup(
            DialogoErroLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoErroLoginLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(ErroDialogo)
                .addGap(18, 18, 18)
                .addComponent(BotaoOkDialogoErro)
                .addGap(28, 28, 28))
        );

        BotaoOkDialogoSucesso.setText("OK");
        BotaoOkDialogoSucesso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoOkDialogoSucessoMouseClicked(evt);
            }
        });
        BotaoOkDialogoSucesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoOkDialogoSucessoActionPerformed(evt);
            }
        });

        TextoSucessoDialogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoSucessoDialogo.setText("LOL");

        javax.swing.GroupLayout BemVindoDialogoLayout = new javax.swing.GroupLayout(BemVindoDialogo.getContentPane());
        BemVindoDialogo.getContentPane().setLayout(BemVindoDialogoLayout);
        BemVindoDialogoLayout.setHorizontalGroup(
            BemVindoDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BemVindoDialogoLayout.createSequentialGroup()
                .addGroup(BemVindoDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BemVindoDialogoLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(BotaoOkDialogoSucesso, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BemVindoDialogoLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(TextoSucessoDialogo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(123, 123, 123))
        );
        BemVindoDialogoLayout.setVerticalGroup(
            BemVindoDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BemVindoDialogoLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(TextoSucessoDialogo)
                .addGap(18, 18, 18)
                .addComponent(BotaoOkDialogoSucesso)
                .addGap(28, 28, 28))
        );

        DialogoErroAplic.setAlwaysOnTop(false);

        ErroDialogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ErroDialogo1.setText("Nome ou data de nascimento em branco!");

        BotaoOkErroAplic.setText("OK");
        BotaoOkErroAplic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoOkErroAplicMouseClicked(evt);
            }
        });
        BotaoOkErroAplic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoOkErroAplicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogoErroAplicLayout = new javax.swing.GroupLayout(DialogoErroAplic.getContentPane());
        DialogoErroAplic.getContentPane().setLayout(DialogoErroAplicLayout);
        DialogoErroAplicLayout.setHorizontalGroup(
            DialogoErroAplicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoErroAplicLayout.createSequentialGroup()
                .addGroup(DialogoErroAplicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogoErroAplicLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(BotaoOkErroAplic, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DialogoErroAplicLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(ErroDialogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81))
        );
        DialogoErroAplicLayout.setVerticalGroup(
            DialogoErroAplicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoErroAplicLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(ErroDialogo1)
                .addGap(18, 18, 18)
                .addComponent(BotaoOkErroAplic)
                .addGap(28, 28, 28))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NeedleSoft");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImages(null);
        setMaximumSize(new java.awt.Dimension(800, 537));
        setMinimumSize(new java.awt.Dimension(400, 517));
        setName("FramePrincipal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 517));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 517));

        FrameLogin.setBackground(new java.awt.Color(255, 255, 255));
        FrameLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(80, 101, 132)));
        FrameLogin.setMaximumSize(new java.awt.Dimension(413, 517));
        FrameLogin.setMinimumSize(new java.awt.Dimension(413, 517));
        FrameLogin.setPreferredSize(new java.awt.Dimension(413, 517));

        CampoUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CampoUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoUsuario.setToolTipText("Nome de usuário");
        CampoUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(80, 101, 132)));
        CampoUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoUsuarioFocusGained(evt);
            }
        });
        CampoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoUsuarioMouseClicked(evt);
            }
        });

        CampoSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoSenha.setToolTipText("Senha do usuário");
        CampoSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(80, 101, 132)));
        CampoSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoSenhaFocusGained(evt);
            }
        });
        CampoSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoSenhaMouseClicked(evt);
            }
        });
        CampoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoSenhaActionPerformed(evt);
            }
        });

        botaologin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaologin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoprog/button.png"))); // NOI18N
        botaologin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaologinMouseClicked(evt);
            }
        });

        LogoSoftware.setIcon(new javax.swing.ImageIcon("C:\\Users\\kesley\\Pictures\\needlesoft.png")); // NOI18N

        IconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoprog/icons8-User-30.png"))); // NOI18N

        IconPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoprog/icons8-Password-30.png"))); // NOI18N

        javax.swing.GroupLayout FrameLoginLayout = new javax.swing.GroupLayout(FrameLogin);
        FrameLogin.setLayout(FrameLoginLayout);
        FrameLoginLayout.setHorizontalGroup(
            FrameLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FrameLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameLoginLayout.createSequentialGroup()
                        .addComponent(LogoSoftware, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameLoginLayout.createSequentialGroup()
                        .addGroup(FrameLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IconPass)
                            .addComponent(IconUser, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FrameLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampoSenha)
                            .addComponent(CampoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(258, 258, 258))))
            .addGroup(FrameLoginLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(botaologin, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        FrameLoginLayout.setVerticalGroup(
            FrameLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameLoginLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(LogoSoftware, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(FrameLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CampoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IconUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrameLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IconPass))
                .addGap(18, 18, 18)
                .addComponent(botaologin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        FrameMenuPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        MenuTabs.setBackground(new java.awt.Color(255, 255, 255));
        MenuTabs.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(80, 101, 132)));
        MenuTabs.setPreferredSize(new java.awt.Dimension(700, 700));

        PainelCadastrarPaciente.setBackground(new java.awt.Color(255, 255, 255));
        PainelCadastrarPaciente.setPreferredSize(new java.awt.Dimension(425, 537));

        TextoNome.setText("Nome:");

        TextoDataNascimento.setText("Data de Nascimento:");

        TextoSexo.setText("Sexo:");

        CampoNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CampoNome.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(80, 101, 132)));
        CampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNome3ActionPerformed(evt);
            }
        });

        CampoDataDeNascimento.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(80, 101, 132)));
        CampoDataDeNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDataDeNascimento3CampoDataDeNascimentoActionPerformed(evt);
            }
        });

        BotaoSalvarCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoprog/icons8-Save-20.png"))); // NOI18N
        BotaoSalvarCadastro.setText("Salvar");
        BotaoSalvarCadastro.setBorder(null);
        BotaoSalvarCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoSalvarCadastro3BotaoSalvarCadastroMouseClicked(evt);
            }
        });

        BotaoLimparCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoprog/icons8-Erase-20.png"))); // NOI18N
        BotaoLimparCadastro.setText("Limpar");
        BotaoLimparCadastro.setMaximumSize(new java.awt.Dimension(55, 21));
        BotaoLimparCadastro.setMinimumSize(new java.awt.Dimension(55, 21));
        BotaoLimparCadastro.setPreferredSize(new java.awt.Dimension(55, 21));
        BotaoLimparCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoLimparCadastro3BotaoLimparCadastroMouseClicked(evt);
            }
        });

        GrupoSexo.add(BotaoMasculino);
        BotaoMasculino.setText("Masculino");

        GrupoSexo.add(BotaoFeminino);
        BotaoFeminino.setText("Feminino");

        javax.swing.GroupLayout PainelCadastrarPacienteLayout = new javax.swing.GroupLayout(PainelCadastrarPaciente);
        PainelCadastrarPaciente.setLayout(PainelCadastrarPacienteLayout);
        PainelCadastrarPacienteLayout.setHorizontalGroup(
            PainelCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastrarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCadastrarPacienteLayout.createSequentialGroup()
                        .addComponent(TextoNome)
                        .addGap(10, 10, 10)
                        .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextoDataNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextoSexo)
                        .addGap(15, 15, 15)
                        .addComponent(BotaoMasculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoFeminino))
                    .addGroup(PainelCadastrarPacienteLayout.createSequentialGroup()
                        .addComponent(BotaoSalvarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoLimparCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelCadastrarPacienteLayout.setVerticalGroup(
            PainelCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastrarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoSalvarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoLimparCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(PainelCadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoNome)
                    .addComponent(TextoDataNascimento)
                    .addComponent(CampoDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoSexo)
                    .addComponent(BotaoMasculino)
                    .addComponent(BotaoFeminino))
                .addContainerGap(446, Short.MAX_VALUE))
        );

        MenuTabs.addTab("Cadastrar Paciente", PainelCadastrarPaciente);

        PainelAplicarVacinas.setBackground(new java.awt.Color(255, 255, 255));

        TextoNomeAplic.setText("Nome:");

        TextoVacina.setText("Vacina:");

        DataAplic.setText("Data de Vacinação: ");

        CaixaFebreAmarela.setText("Febre Amarela");

        CaixaHPV.setText("HPV");

        CaixaTripliceViral.setText("Tríplice Viral");

        CaixaAntiTetanica.setText("Anti Tetânica");

        CaixaHepatiteB.setText("Hepatite B");

        CaixaTetraViral.setText("Tetraviral");

        CaixaPentavalente.setText("Pentavalente");

        CaixaBCG.setText("BCG");

        CaixadTpa.setText("dTpa");

        CaixaGripe.setText("Gripe");

        BotaoSalvarAplic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoprog/icons8-Save-20.png"))); // NOI18N
        BotaoSalvarAplic.setText("Salvar");
        BotaoSalvarAplic.setBorder(null);
        BotaoSalvarAplic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoSalvarAplicBotaoSalvarCadastroMouseClicked(evt);
            }
        });

        BotaoLimparAplic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoprog/icons8-Erase-20.png"))); // NOI18N
        BotaoLimparAplic.setText("Limpar");
        BotaoLimparAplic.setMaximumSize(new java.awt.Dimension(55, 21));
        BotaoLimparAplic.setMinimumSize(new java.awt.Dimension(55, 21));
        BotaoLimparAplic.setPreferredSize(new java.awt.Dimension(55, 21));
        BotaoLimparAplic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoLimparAplicBotaoLimparCadastroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PainelAplicarVacinasLayout = new javax.swing.GroupLayout(PainelAplicarVacinas);
        PainelAplicarVacinas.setLayout(PainelAplicarVacinasLayout);
        PainelAplicarVacinasLayout.setHorizontalGroup(
            PainelAplicarVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAplicarVacinasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelAplicarVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelAplicarVacinasLayout.createSequentialGroup()
                        .addComponent(BotaoSalvarAplic, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoLimparAplic, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelAplicarVacinasLayout.createSequentialGroup()
                        .addComponent(TextoNomeAplic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoNomeAplic, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DataAplic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoDataAplic, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelAplicarVacinasLayout.createSequentialGroup()
                        .addComponent(TextoVacina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelAplicarVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelAplicarVacinasLayout.createSequentialGroup()
                                .addComponent(CaixaHepatiteB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CaixaTetraViral)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CaixaPentavalente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CaixaBCG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CaixadTpa))
                            .addGroup(PainelAplicarVacinasLayout.createSequentialGroup()
                                .addComponent(CaixaGripe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CaixaFebreAmarela)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CaixaHPV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CaixaTripliceViral)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CaixaAntiTetanica)))))
                .addContainerGap(401, Short.MAX_VALUE))
        );
        PainelAplicarVacinasLayout.setVerticalGroup(
            PainelAplicarVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAplicarVacinasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelAplicarVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoSalvarAplic, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoLimparAplic, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelAplicarVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoNomeAplic)
                    .addComponent(CampoNomeAplic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DataAplic)
                    .addComponent(CampoDataAplic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(PainelAplicarVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoVacina)
                    .addComponent(CaixaGripe)
                    .addComponent(CaixaFebreAmarela)
                    .addComponent(CaixaHPV)
                    .addComponent(CaixaTripliceViral)
                    .addComponent(CaixaAntiTetanica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelAplicarVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CaixaHepatiteB)
                    .addComponent(CaixaTetraViral)
                    .addComponent(CaixaPentavalente)
                    .addComponent(CaixaBCG)
                    .addComponent(CaixadTpa))
                .addContainerGap(519, Short.MAX_VALUE))
        );

        MenuTabs.addTab("Aplicar Vacinas", PainelAplicarVacinas);

        PainelVisualizarCarteira.setBackground(new java.awt.Color(255, 255, 255));
        PainelVisualizarCarteira.setPreferredSize(new java.awt.Dimension(800, 800));

        LabelNomeBuscarCarteira.setText("Nome:");

        BotaoBuscarCarteira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoprog/icons8-Search-20.png"))); // NOI18N
        BotaoBuscarCarteira.setText("Buscar");
        BotaoBuscarCarteira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoBuscarCarteiraMouseClicked(evt);
            }
        });

        TextoVacinas.setEditable(false);
        TextoVacinas.setColumns(20);
        TextoVacinas.setRows(5);

        TextoData.setEditable(false);
        TextoData.setColumns(20);
        TextoData.setRows(5);

        TextoColunaVacina.setEditable(false);
        TextoColunaVacina.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextoColunaVacina.setText("Vacinas");

        TextoColunaDataDeVacinacao.setEditable(false);
        TextoColunaDataDeVacinacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextoColunaDataDeVacinacao.setText("Data De Vacinação");
        TextoColunaDataDeVacinacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoColunaDataDeVacinacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelVisualizarCarteiraLayout = new javax.swing.GroupLayout(PainelVisualizarCarteira);
        PainelVisualizarCarteira.setLayout(PainelVisualizarCarteiraLayout);
        PainelVisualizarCarteiraLayout.setHorizontalGroup(
            PainelVisualizarCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelVisualizarCarteiraLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(PainelVisualizarCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PainelVisualizarCarteiraLayout.createSequentialGroup()
                        .addComponent(TextoVacinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextoData))
                    .addGroup(PainelVisualizarCarteiraLayout.createSequentialGroup()
                        .addComponent(LabelNomeBuscarCarteira)
                        .addGap(18, 18, 18)
                        .addComponent(CampoNomeBuscarCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoBuscarCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelVisualizarCarteiraLayout.createSequentialGroup()
                        .addComponent(TextoColunaVacina, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextoColunaDataDeVacinacao, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(293, Short.MAX_VALUE))
        );
        PainelVisualizarCarteiraLayout.setVerticalGroup(
            PainelVisualizarCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelVisualizarCarteiraLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(PainelVisualizarCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNomeBuscarCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNomeBuscarCarteira)
                    .addComponent(BotaoBuscarCarteira))
                .addGap(18, 18, 18)
                .addGroup(PainelVisualizarCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoColunaVacina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoColunaDataDeVacinacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelVisualizarCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoVacinas, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoData, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(332, Short.MAX_VALUE))
        );

        MenuTabs.addTab("Visualizar Carteira de Vacinação", PainelVisualizarCarteira);

        javax.swing.GroupLayout FrameMenuPrincipalLayout = new javax.swing.GroupLayout(FrameMenuPrincipal);
        FrameMenuPrincipal.setLayout(FrameMenuPrincipalLayout);
        FrameMenuPrincipalLayout.setHorizontalGroup(
            FrameMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameMenuPrincipalLayout.createSequentialGroup()
                .addComponent(MenuTabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        FrameMenuPrincipalLayout.setVerticalGroup(
            FrameMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameMenuPrincipalLayout.createSequentialGroup()
                .addComponent(MenuTabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 534, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FrameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FrameMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FrameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FrameMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        FrameLogin.setVisible(true);
        FrameMenuPrincipal.setVisible(false);

        setSize(new java.awt.Dimension(421, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoOkDialogoErroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoOkDialogoErroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoOkDialogoErroActionPerformed

    private void BotaoOkDialogoErroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoOkDialogoErroMouseClicked
        DialogoErroLogin.setVisible(false);
    }//GEN-LAST:event_BotaoOkDialogoErroMouseClicked

    private void BotaoOkDialogoSucessoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoOkDialogoSucessoMouseClicked
        BemVindoDialogo.setVisible(false);
       new GUI().setVisible(false);

    }//GEN-LAST:event_BotaoOkDialogoSucessoMouseClicked

    private void BotaoOkDialogoSucessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoOkDialogoSucessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoOkDialogoSucessoActionPerformed

    private void BotaoOkErroAplicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoOkErroAplicMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoOkErroAplicMouseClicked

    private void BotaoOkErroAplicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoOkErroAplicActionPerformed
        DialogoErroAplic.setVisible(false);
    }//GEN-LAST:event_BotaoOkErroAplicActionPerformed

    private void CampoUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoUsuarioFocusGained
        CampoUsuario.setText("");
    }//GEN-LAST:event_CampoUsuarioFocusGained

    private void CampoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoUsuarioMouseClicked
        CampoUsuario.setText("");
    }//GEN-LAST:event_CampoUsuarioMouseClicked

    private void CampoSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoSenhaFocusGained
        CampoSenha.setText("");
    }//GEN-LAST:event_CampoSenhaFocusGained

    private void CampoSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoSenhaMouseClicked
        CampoSenha.setText("");
    }//GEN-LAST:event_CampoSenhaMouseClicked

    private void CampoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoSenhaActionPerformed
        CampoSenha.setText("");
    }//GEN-LAST:event_CampoSenhaActionPerformed

    private void botaologinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaologinMouseClicked
        String Usuario = CampoUsuario.getText();
        String Senha;
        Senha = new String (CampoSenha.getPassword());
        loginUsuario login;
        login = new loginUsuario();
        try {
            if(login.LoginUsuario(Usuario, Senha)){
                setLocationRelativeTo(null);
                setSize(new java.awt.Dimension(760, 560));
                FrameLogin.setVisible(false);
                FrameMenuPrincipal.setVisible(true);
            }
            else{
                DialogoErroLogin.pack();
                DialogoErroLogin.setVisible(true);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaologinMouseClicked

    private void TextoColunaDataDeVacinacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoColunaDataDeVacinacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoColunaDataDeVacinacaoActionPerformed

    private void BotaoBuscarCarteiraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoBuscarCarteiraMouseClicked
        VisualizarCarteira visualizar = new VisualizarCarteira();
        String NomeBusca = CampoNomeBuscarCarteira.getText();
        String[] arr = visualizar.VisualizarVacinas(NomeBusca);
        String str = String.join("\n\n", arr);
        TextoVacinas.setText(str);
        String[] arr2 = visualizar.VisualizarDatas(NomeBusca);
        String str2 = String.join("\n\n", arr2);
        TextoData.setText(str2);
    }//GEN-LAST:event_BotaoBuscarCarteiraMouseClicked

    private void BotaoLimparAplicBotaoLimparCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoLimparAplicBotaoLimparCadastroMouseClicked
        CampoNomeAplic.setText("");
        CampoDataAplic.setText("");
        CaixaAntiTetanica.setSelected(false);
        CaixaBCG.setSelected(false);
        CaixaFebreAmarela.setSelected(false);
        CaixaGripe.setSelected(false);
        CaixaHPV.setSelected(false);
        CaixaHepatiteB.setSelected(false);
        CaixaPentavalente.setSelected(false);
        CaixaTetraViral.setSelected(false);
        CaixaTripliceViral.setSelected(false);
        CaixadTpa.setSelected(false);
    }//GEN-LAST:event_BotaoLimparAplicBotaoLimparCadastroMouseClicked

    private void BotaoSalvarAplicBotaoSalvarCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoSalvarAplicBotaoSalvarCadastroMouseClicked
        String NomeAplic;
        String DataAplicacao;
        int contador=0;
        DataAplicacao = CampoDataAplic.getText();
        NomeAplic = CampoNomeAplic.getText();
        boolean aplicacao;

        String Vacinas = "";
        AplicacaoVacinas aplicar;
        aplicar = new AplicacaoVacinas();
        if (CaixaAntiTetanica.isSelected()) {
            Vacinas += "AntiTetânica.";
            contador++;
}
         if (CaixaBCG.isSelected()) {
            Vacinas += "BCG.";
            contador++;
}
          if (CaixaFebreAmarela.isSelected()) {
            Vacinas += "Febre Amarela.";
            contador++;
}
           if (CaixaGripe.isSelected()) {
            Vacinas += "Gripe.";
            contador++;
}
            if (CaixaHPV.isSelected()) {
            Vacinas += "HPV.";
            contador++;
}
             if (CaixaHepatiteB.isSelected()) {
            Vacinas += "Hepatite B.";
            contador++;
}
              if (CaixaPentavalente.isSelected()) {
            Vacinas += "Pentavalente.";
            contador++;
}
              if (CaixaTetraViral.isSelected()) {
            Vacinas += "Tetraviral.";
            contador++;
}
                if (CaixaTripliceViral.isSelected()) {
            Vacinas += "Triplice Viral.";
            contador++;
}
                  if (CaixadTpa.isSelected()) {
            Vacinas += "dTpa.";
            contador++;
}





          if ( DataAplicacao.equals("") || NomeAplic.equals("")){
            DialogoErroAplic.pack();
            DialogoErroAplic.setVisible(true);
        }
          else{
               try {
           aplicacao = aplicar.GravarAplicVacinas(NomeAplic, DataAplicacao, Vacinas, contador);
           if(aplicacao!=true){
               System.out.println("ERRO");
           }
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
          }
    }//GEN-LAST:event_BotaoSalvarAplicBotaoSalvarCadastroMouseClicked

    private void BotaoLimparCadastro3BotaoLimparCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoLimparCadastro3BotaoLimparCadastroMouseClicked
        CampoNome.setText("");
        //CampoSexo.setText("");
        CampoDataDeNascimento.setText("");
    }//GEN-LAST:event_BotaoLimparCadastro3BotaoLimparCadastroMouseClicked

    private void BotaoSalvarCadastro3BotaoSalvarCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoSalvarCadastro3BotaoSalvarCadastroMouseClicked
        String Nome = CampoNome.getText();
        String DataDeNascimento = CampoDataDeNascimento.getText();
          String Sexo = null;
        if(BotaoMasculino.isSelected()){
            Sexo = BotaoMasculino.getText();
        }
        else if(BotaoFeminino.isSelected()){
             Sexo = BotaoFeminino.getText();
        }
        CadastroPaciente cadastro = new CadastroPaciente();
        cadastro.CadastrarPaciente(Nome, DataDeNascimento, Sexo);
    }//GEN-LAST:event_BotaoSalvarCadastro3BotaoSalvarCadastroMouseClicked

    private void CampoDataDeNascimento3CampoDataDeNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDataDeNascimento3CampoDataDeNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoDataDeNascimento3CampoDataDeNascimentoActionPerformed

    private void CampoNome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNome3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNome3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog BemVindoDialogo;
    private javax.swing.JButton BotaoBuscarCarteira;
    private javax.swing.JRadioButton BotaoFeminino;
    private javax.swing.JButton BotaoLimparAplic;
    private javax.swing.JButton BotaoLimparCadastro;
    private javax.swing.JRadioButton BotaoMasculino;
    private javax.swing.JButton BotaoOkDialogoErro;
    private javax.swing.JButton BotaoOkDialogoSucesso;
    private javax.swing.JButton BotaoOkErroAplic;
    private javax.swing.JButton BotaoSalvarAplic;
    private javax.swing.JButton BotaoSalvarCadastro;
    private javax.swing.JCheckBox CaixaAntiTetanica;
    private javax.swing.JCheckBox CaixaBCG;
    private javax.swing.JCheckBox CaixaFebreAmarela;
    private javax.swing.JCheckBox CaixaGripe;
    private javax.swing.JCheckBox CaixaHPV;
    private javax.swing.JCheckBox CaixaHepatiteB;
    private javax.swing.JCheckBox CaixaPentavalente;
    private javax.swing.JCheckBox CaixaTetraViral;
    private javax.swing.JCheckBox CaixaTripliceViral;
    private javax.swing.JCheckBox CaixadTpa;
    private javax.swing.JTextField CampoDataAplic;
    private javax.swing.JFormattedTextField CampoDataDeNascimento;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JTextField CampoNomeAplic;
    private javax.swing.JTextField CampoNomeBuscarCarteira;
    private javax.swing.JPasswordField CampoSenha;
    private javax.swing.JTextField CampoUsuario;
    private javax.swing.JLabel DataAplic;
    private javax.swing.JDialog DialogoErroAplic;
    private javax.swing.JDialog DialogoErroLogin;
    private javax.swing.JLabel ErroDialogo;
    private javax.swing.JLabel ErroDialogo1;
    private javax.swing.JPanel FrameLogin;
    private javax.swing.JPanel FrameMenuPrincipal;
    private javax.swing.ButtonGroup GrupoSexo;
    private javax.swing.JLabel IconPass;
    private javax.swing.JLabel IconUser;
    private javax.swing.JLabel LabelNomeBuscarCarteira;
    private javax.swing.JLabel LogoSoftware;
    private javax.swing.JTabbedPane MenuTabs;
    private javax.swing.JPanel PainelAplicarVacinas;
    private javax.swing.JPanel PainelCadastrarPaciente;
    private javax.swing.JPanel PainelVisualizarCarteira;
    private javax.swing.JTextField TextoColunaDataDeVacinacao;
    private javax.swing.JTextField TextoColunaVacina;
    private javax.swing.JTextArea TextoData;
    private javax.swing.JLabel TextoDataNascimento;
    private javax.swing.JLabel TextoNome;
    private javax.swing.JLabel TextoNomeAplic;
    private javax.swing.JLabel TextoSexo;
    private javax.swing.JLabel TextoSucessoDialogo;
    private javax.swing.JLabel TextoVacina;
    private javax.swing.JTextArea TextoVacinas;
    private javax.swing.JLabel botaologin;
    // End of variables declaration//GEN-END:variables

}
